services:
  web:
    build: .
    container_name: flask_app
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./dockerized_app:/app
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: db
    ports:
      - "5439:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  db2:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: db2
    ports:
      - "5433:5432"
    volumes:
      - postgres_data2:/var/lib/postgresql/data
  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"
    depends_on:
      - db
volumes:
  postgres_data:
  postgres_data2:

