name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: 🛎️ Клонируем репозиторий
        uses: actions/checkout@v3

      - name: 📦 Устанавливаем Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13  # ставь свою версию

      - name: 📥 Устанавливаем зависимости
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 🔍 Линтинг (ruff)
        run: |
          pip install "ruff>=0.4.0"
          ruff check .

      - name: 📂 Установка PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)" >> $GITHUB_ENV

      - name: ✅ Запускаем тесты
        run: |
          pip install pytest
          pytest